### ISSUE TITLE
Should we use `set` instead of `add` ?

### ISSUE THREAD

**Issue by Xanonymous-GitHub** [ricky9667/smart_space#15]
Should we use `set` instead of `add` ?
Not sure the origin design of this step. Is it expect for "update the existing data on the cloud" or "add a random mock data to the cloud"?

_Originally posted by @Xanonymous-GitHub in https://github.com/ricky9667/smart_space/pull/14#discussion_r1027778222_

**Comment by ricky9667** [comment]
We remain using `set` for firebase. 
The webpage will read the newest data from firebase, and data in the webpage will be gone if refreshed.
